version: '3'
services:
  web:
    build: .
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8011:8000"
    depends_on:
      - db
    restart: on-failure:10

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=akremdb
      - POSTGRES_USER=akrem
      - POSTGRES_PASSWORD=akrempass
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  
